# Generated by Django 3.0 on 2021-01-05 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('dataform', '0001_initial'), ('dataform', '0002_auto_20210102_1530'), ('dataform', '0003_auto_20210102_1600'), ('dataform', '0004_auto_20210102_1634'), ('dataform', '0005_auto_20210102_1831')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=14)),
                ('mes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/form/%Y/%m/%d')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataform.EmailForm')),
            ],
        ),
    ]
