# Generated by Django 3.0 on 2021-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=14)),
                ('mes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d')),
            ],
        ),
    ]
