# Generated by Django 3.0 on 2021-01-02 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailform',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
