# Generated by Django 3.0 on 2021-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataform', '0002_auto_20210102_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailform',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
