# Generated by Django 3.0 on 2021-01-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataform', '0004_auto_20210102_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailform',
            name='image',
        ),
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/form/%Y/%m/%d')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataform.EmailForm')),
            ],
        ),
    ]
